version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 100
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 50
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
      ignored-numbers:
        - "0"
        - "1"
    revive:
      confidence: 0.8
      enable-all-rules: true
      rules:
        - name: cognitive-complexity
          disabled: true
        - name: argument-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: file-header
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: struct-tag
          disabled: true
        - name: add-constant
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: nested-structs
          disabled: true
        - name: use-errors-new
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocognit
          - mnd
        path: _test\.go
    paths:
      - test/
      - internal/deepmap/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/grafana/grafana-app-sdk
  exclusions:
    generated: lax
    paths:
      - test/
      - internal/deepmap/
      - third_party$
      - builtin$
      - examples$
